#               ::: touch $HOME/.tmux.conf


# Change prefix key to CTRL+A. "C-" stands for CTRL, "M-" stands for ALT key

set-option -g prefix C-k
unbind-key C-b
bind-key C-k send-prefix

set-option -g prefix M-a
unbind-key C-b
bind-key M-a send-prefix

#     @ : source-file ~/.tmux.conf   ===    @ r         
#                   
#         cargar archivo de configuraci[on propio <3
