#               ::: touch $HOME/.tmux.conf
#  @ : source-file ~/.tmux.conf   ===    @ r         

setw -g mode-keys vi
set -g status-justify centre

# Change prefix key to CTRL+A. "C-" stands for CTRL, "M-" stands for ALT key
set-option -g prefix M-m # set-option -g prefix C-k       M-a
unbind-key C-b
bind-key M-m send-prefix # bind-key C-k send-prefix       M-a

bind-key C-i last-window    # salto ultima Pesta~a usada
bind M-x new-session  # @ Alt x     @ Ctrl x     createNewSession  #bind C-c new-session

# pane navigation
bind -r h select-pane -L  # move left
bind -r j select-pane -D  # move down
bind -r k select-pane -U  # move up
bind -r l select-pane -R  # move right

#pane resizing
bind -r H resize-pane -L 6
bind -r J resize-pane -D 6
bind -r K resize-pane -U 6
bind -r L resize-pane -R 6

bind > swap-pane -D       # swap current pane with the next one   @ }
bind < swap-pane -U       # swap current pane with the previous one @ {

# find session
#bind C-f command-prompt -p find-session 'switch-client -t %%'

# split current window horizontally - vertically
unbind %
unbind '"'
bind - split-window -v -c '#{pane_current_path}'  # @ "
bind _ split-window -h -c '#{pane_current_path}' # @ %
bind '"' split-window -fv -c '#{pane_current_path}'  # @ "    divisionesBruscas/Generales
bind % split-window -fh -c '#{pane_current_path}' # @ %       divisionesBruscas/Generales

# open new panes in current path
bind c new-window -c '#{pane_current_path}'

set -g renumber-windows on    # renumber windows when a window is closed

set-option -g allow-rename off  #evitar que las divisiones_programas cambien el nombre de la pesta~a

bind r source-file ~/.tmux.conf \; display " ::: alone but free... the master of my destin... UmU"

set -g status-fg "#22FF00"
#set -g status-bg "#291F1F"
set -g status-bg colour235

#set -g visual-activity on
#setw -g monitor-activity on

#Pane colours
# set inactive/active window styles
#set -g window-style 'fg=colour250,bg=colour233'
#set -g window-active-style 'fg=colour255,bg=black'

# Status line left side
# Session: X Y Z settings
set -g status-left-length 80 
#set -g status-left "#[fg=colour84] > #S #[fg=colour243] #I#[fg=colour213]#P "

#Time and date on right-hand side
# Status line right side
# e.g. 28 Nov 18:15


set -g status-right-length 90 
#set -g status-right "#[fg=colour245]%d %b #[fg=colour14] %R "
#statusline BATTERY begin
set -g status-right "(￣ヘ￣;)^ω^）#(upower --dump 2>/dev/null | grep -E 'DisplayDevice' -A 15 | grep -E 'state|percentage' | awk '{print $2}' | tr '\n' ':' | tr '[:lower:]' '[:upper:]' )  #[fg=colour245]%d %b #[fg=colour14] %R "
#statusline BATTERY end

set -g status-interval 10
